before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: connectedp-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  ldflags:
    - -s -w -X github.com/k1LoW/connectedp.version={{.Version}} -X github.com/k1LoW/connectedp.commit={{.FullCommit}} -X github.com/k1LoW/connectedp.date={{.Date}} -X github.com/k1LoW/connectedp/version.Version={{.Version}}
archives:
-
  id: connectedp-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
-
  name: connectedp
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/connectedp
  description: 'Check your MacBook power cable connection.'
  install: bin.install 'connectedp'
